LinkedInSystem Design
1. 已知一个函数，输入用户ID，可以返回该用户的所有好友(degree 1 friends)，并且能够实现按照好友ID从小到大排序。现要求实现算法和相关的系统，返回一个用户的所有好友的好友(degree 2 friends), 以及degree 3 friends。
Note: 通过临时加一些限制条件，能够进行时间或空间的优化。

2. 已知一个文件系统，可以create files, delete files, sequentially scan file content, read file content randomly, append file content.对于key-value pairs，在给定的文件系统中实现put，get，delete 方法。其中key比较小，全部key可以放在内存中，value会比较大。
Answer:
a. In the main memory, maintain a hashmap, key is the given input key, value is thefile ptr and line ptr(key-value pair location in the file system).

b. Each time we need to update the value, write a new key value pair at the end of the file, and also update the related key value pairs in the main memory. Then when main memory cracks, we can reconstruct the main memory hashmap from the files content.

c. Merge: 
Make file modifications to save space: scan the file sequentially for each key to find the latest update, then put the latest key-value pairs into another file. After we finished doing this for all the keys in a file, delete that file.

d. Deal with synchronization: when we do the file modification, put all the newest updates into another file, then replay it.

e. Each file should have a limited amount of different keys, so that file modification is not that hard.

3. Design Tiny URL/ Note: 如何配置Memcache。

4. Design LinkedIn
a. Search功能里inverted index 和data of user , data of company 怎么存，分别用NoSQL还是SQL?-> 列举了NoSQL和SQL区别，最后选择SQL。

b. 前端模块的service/ application区别。
c. 设计timeline，push / pull model。
5. How to design LinkedIn profile page which can support rich media such as vide0, picture and audio?
6. LinkedIn有很多host server在做很多不同的service，这些service发出的exception都会被写到log里。设计一个系统，监测24小时之内top 500的exceptions。
7. How to design the API for searching similar people?
 Details about the frontend / backend.
8. Design a system tocal culate the revenues generated by ad click.
9. 设计系统来实现5分钟，1小时，24小时内分享前10多的文章/ Note:Distributed System

10. 社交网站上的文章转发，如何设计系统可以得到实时的转发量榜单和weekly digest，要求数据库的设计。有人转发一个文章时request是什么样的，如何快速得到实时的转发量榜单，如何得到weekly digest等。Note:
a. weekly digest就把每转发一次的信息存入到数据库中，然后直接读取就行了。
b. 实时转发我说可以保存到一个in-memory database里面，可以快速读取。

11. Design IP Black List
这个考虑起来很有意思，先要问问是IPv4还是IPv6. 前者所有地址加起来共有2^32个，如果内存足够大，一个BITMAP在O(1)就搞定了。如果内存不够或者是IPv6，那就考虑分块，多级索引，二分查找，反正复杂度立刻上升为是O(LOG)，当然可以详细讨论这个LOG具体怎么做。
12. Design a recommendation system 
Data collection / Training algorithm / Evaluate recommendation results / Evolve with C 
13. 假设现在我们有N个服务器，每个服务器有一个check sum，如果黑客攻击其中某一个服务器，那么该服务器的check sum就会改变，一旦改变，就是被黑客攻击了。设计一个系统，如何detect hacker attack。
14. 设计Amazon Buy页面
a. 如何设计database来存信息，然后render page? 用SQL来存各个table。 
b. 如果数据很大怎么办? 
可以把shared data存在各个slave上，靠master去query，然后OOD server interface，怎样读取各个table的信息，然后写了一个server class来用这些interface来render page。 
c. 如果很多客户同时读怎么办，我的解决方法有cache / multi-threading。 
d. How to suggest product，建一个Product weighted graph, 然后用BFS。

15. Design a dashboard system for administrator to monitor the top URL in last 5 minutes. 
Note: high traffic, database schema design, user experience, performance issue, communication protocol, etc. 
16. Design a notebook application like evernote or onenote, it should support search and collaboration operations.

17. 一个user enter company or university information while signing on, how to help the user better locate his company / university? 
我先说用hashtable存company / university 和id pairs，然后用Trie实现auto-completion帮助user完成look-up。如果High-level怎么快速locate？可以combine location, rank of the top selected company / university, connection’s company / university, logo来推荐。如果用户填资料的时候没有选对应的选项，自己填了一个怎么办？可以暂时存null，之后再让用户complete information。 
http://systemdesigns.blogspot.com/2015/12/blog-post_7.html
